---
title: "Yield Curve Musings"
author: "Ben Jaletzke"
date: ""
summary: "Some Graphs on the US Yield Curve and Financial Data"
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
---


```{r, setup, echo=FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE, 
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
options(digits = 3)

# default figure size
knitr::opts_chunk$set(
  fig.width=6.75, 
  fig.height=6.75,
  fig.align = "center"
)
```


```{r load-libraries, echo=FALSE}
library(tidyverse)  # Load ggplot2, dplyr, and all the other tidyverse packages
library(mosaic)
library(ggthemes)
library(GGally)
library(readxl)
library(here)
library(skimr)
library(janitor)
library(broom)
library(tidyquant)
library(infer)
library(openintro)
library(tidyquant)
library(stats)
```


```{r get_rates, warning=FALSE}
# Get a list of FRED codes for US rates and US yield curve; choose monthly frequency
# to see, eg., the 3-month T-bill https://fred.stlouisfed.org/series/TB3MS
tickers <- c('TB3MS', # 3-month Treasury bill (or T-bill)
             'TB6MS', # 6-month
             'GS1',   # 1-year
             'GS2',   # 2-year, etc....
             'GS3',
             'GS5',
             'GS7',
             'GS10',
             'GS20',
             'GS30')  #.... all the way to the 30-year rate

# Turn  FRED codes to human readable variables
myvars <- c('3-Month Treasury Bill',
            '6-Month Treasury Bill',
            '1-Year Treasury Rate',
            '2-Year Treasury Rate',
            '3-Year Treasury Rate',
            '5-Year Treasury Rate',
            '7-Year Treasury Rate',
            '10-Year Treasury Rate',
            '20-Year Treasury Rate',
            '30-Year Treasury Rate')

maturity <- c('3m', '6m', '1y', '2y','3y','5y','7y','10y','20y','30y')

# by default R will sort these maturities alphabetically; but since we want
# to keep them in that exact order, we recast maturity as a factor 
# or categorical variable, with the levels defined as we want
maturity <- factor(maturity, levels = maturity)

# Create a lookup dataset
mylookup<-data.frame(symbol=tickers,var=myvars, maturity=maturity)
# Take a look:
mylookup %>% 
  knitr::kable()

df <- tickers %>% tidyquant::tq_get(get="economic.data", 
                   from="1960-01-01")   # start from January 1960

glimpse(df)
```



```{r join_data, warning=FALSE}

yield_curve <-left_join(df,mylookup,by="symbol") 

```


### Yields on US rates by duration since 1960

```{r, fig.width = 11, dpi = 220}

yield_curve$var <- factor(yield_curve$var, levels = c("3-Month Treasury Bill",
                                                      "6-Month Treasury Bill",
                                                      "1-Year Treasury Rate",
                                                      "2-Year Treasury Rate",
                                                      "3-Year Treasury Rate",
                                                      "5-Year Treasury Rate",
                                                      "7-Year Treasury Rate",
                                                      "10-Year Treasury Rate",
                                                      "20-Year Treasury Rate",
                                                      "30-Year Treasury Rate"))

ggplot(yield_curve, aes(x = date, y = price, col = var)) +
  geom_line() +
  facet_wrap(~var, ncol = 2) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "",
       y = "%",
       caption = "Source: St. Louis Federal Reserve Economic Database (FRED)",
       title = "Yields on U.S. Treasury rates since 1960")

```

### Monthly yields on US rates by duration since 1999 on a year-by-year basis

```{r, fig.width = 11, dpi = 220}

yield_curve_99 <- yield_curve %>% 
  filter(date > ydm(19983112)) %>% 
  mutate(year = year(date)) %>% 
  mutate(day = format(date, format = "%m-%d"))

ggplot(yield_curve_99) +
  geom_line(aes(x = maturity, y = price, group = day, colour = factor(year))) +
  facet_wrap(~year, ncol = 4) +
  labs(x = "Maturity",
       y = "Yield(%)",
       title = "US Yield Curve",
       caption = "Source: St. Louis Federal Reserve Economic Database (FRED)") +
  theme_bw() +
  theme(legend.position = "none")

```

### 3-month and 10-year yields since 1999


```{r, fig.width = 12, dpi = 220}

yield_curve_99_spr <- yield_curve_99 %>% 
  filter(maturity == "3m" | maturity == "10y")

ggplot(yield_curve_99_spr, aes(x = date, y = price, group = var, colour = var)) +
  geom_line() +
  theme_bw() +
  labs(x = "",
       y = "%",
       title = "Yields on 3-Month and 10-Year US Treasury rates since 1999",
       caption = "Source: St. Louis Federal Reserve Economic Database (FRED)") +
  theme(legend.title = element_blank())

```

According to [Wikipedia's list of recession in the United States](https://en.wikipedia.org/wiki/List_of_recessions_in_the_United_States), since 1999 there have been two recession in the US: between Mar 2001–Nov 2001 and between Dec 2007–June 2009. 

```{r setup_US-recessions, warning=FALSE}

recessions <- tibble(
  from = c("1960-04-01", "1969-12-01", "1973-11-01", "1980-01-01","1981-07-01", "1990-07-01", "2001-03-01", "2007-12-01"),  
  to = c("1961-02-01", "1970-11-01", "1975-03-01", "1980-07-01", "1982-11-01", "1991-03-01", "2001-11-01", "2009-06-01") 
  )  %>% 
  mutate(From = ymd(from), 
         To=ymd(to),
         duration_days = To-From)

recessions
```

```{r, fig.width = 100%}

yield_spread <- yield_curve %>% 
  filter(maturity == "3m" | maturity  == "10y") %>% 
  subset(select = -c(symbol, maturity)) %>%
  pivot_wider(values_from = price, names_from = var) %>% 
  rename(ten_y = `10-Year Treasury Rate`,
         three_m = `3-Month Treasury Bill`) %>% 
  mutate(diff = ten_y - three_m)

ggplot(yield_spread, aes(x = date, y = diff)) +
  geom_ribbon(aes(ymin = 0, ymax = pmax(diff,0)), fill = "#4682B4", colour = "black", alpha = 0.5) +
  geom_ribbon(aes(ymax = 0, ymin = pmin(diff,0)), fill = "#ff3535", colour = "black", alpha = 0.5) +
  geom_rect(data = recessions,
            inherit.aes = FALSE,
            aes(xmin = From, 
                xmax = To, 
                ymin = -Inf, 
                ymax = Inf), 
                fill = "grey", 
                color = "NA",
                alpha = 0.3) +
  geom_rug(color = ifelse(yield_spread$diff>0, "#4682B4", "#ff3535"), 
           size = 0.05, 
           length = unit(0.03, "npc"),
           sides = "b") +
  theme_minimal() +
  theme(legend.position = "none") +
  scale_x_date(date_breaks = "2 years", date_labels = "%Y", limits = as.Date(c('1959-01-01', '2023-01-01'), format="%Y-%M-%D")) +
  labs(x = "",
       y = "Difference (10 year - 3 month) yield in %",
       title = "Yield Curve Inversion: 10-year minus 3-month Treasury rates",
       subtitle = "Difference in % points monthly averages.\nShaded areas correspond to recessions",
       caption = "Source: St. Louis Federal Reserve Economic Database (FRED)")

```
